language: python
python:
- '2.7'
- '3.5'
- '3.6'
install: python setup.py develop
script: nosetests
deploy:
  provider: pypi
  user: adam.shamblin
  password:
    secure: ReqiiBmc/JusV1lcvFtUGX3cwMGFvaAJ4we2deET64RkBpM7UL1UVFDxZ4cbNxmvzqzaQIEp9ee7hIKbHHvFv7g92IuYxPYQEc8y6R9vh8gy240fM7u0kko+3XCFzPD2S88ANnBcOc8MVrb05qCJWy7oFUZ85VpYiP7VEi2IGjmUYN79Z/+nj3hDopUzWHqxH8QrZy/+4I6SAGZVSMYa2d8lGeuSVTfaMEvs1lZBKckORYVocbnKtCALluLqoJg9rrGYMahpQctI5uHJXEr37EJchC95DlEURjDDarzuy7zxAdVo2p4QNldqkMnI8UFh4mJPy2N/4yh9pTwvPxS24ak6LCASII4mjP8eL4xFa7nNxMRq0qKvc2363NeWSyL1NfwTwUE9xE2oRq74QaigyAQs1Awbu7lmjPfh4TkLNxtlnQvDGws7auOOgvRN6NAUGRUGc2Gzv9K/6Ofe8/I0vw/1slgid+qXP7bXnAqGZNVfSDO1p59IhjSdom8BbjkJql+6HZ4UNQXowzSbJJmUj9Q5sgdGWPK6IVdBP4Eb7FK468e7NatuFL+eyjmMKc7vJNy0vOrafMZjsxwengA6mMoVwmyrLvozcLAzt2X6AGUFeryVroxjTfNIEjV1hm4WXPMt1wATN7T/Dh60mTMElEyLiP2BWcdNyXvLEnfT/uU=
  distributions: sdist bdist_wheel
